spring:
  application:
    name: RECEPTION-CMD-MS
  config:
    import: configserver:http://localhost:8888
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      default-zone: http://localhost:8761/eureka
  instance:
    prefer-ip-address: true
#  profiles:
#    active: docker

#logging:
#  file.name: logs/reception_cmd_ms.log
axon:
  serializer:
    general: jackson
    events: jackson
    messages: jackson
management:
  tracing:
    sampling:
      probability: 1.0
#reception-created-topic: "reception-created-topic"