server:
  port: 8084
spring:
  application:
    name: reception_cmd_ms
#  profiles:
#    active: docker
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://localhost:8080/realms/hisclientapp/protocol/openid-connect/certs
  datasource:
    url: jdbc:mysql://localhost:3306/reception_db?createDatabaseIfNotExist=true
    username: root
    password: myhawramRootPsw1
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQL8Dialect
    show-sql: true

kafka-config:
  #  bootstrap-servers: localhost:19092, localhost:29092, localhost:39092
  #  bootstrap-servers: localhost:19092
  bootstrap-servers: localhost:29092
  #  schema-registry-url-key: schema.registry.url
  #  schema-registry-url: http://localhost:8081
  change-visit-status-topic: change-visit-status-topic
  remove-visit-topic: remove-visit-topic
  visit-removed-topic: visit-removed-topic
  reception-removed-topic: reception-removed-topic
  topic-names-to-create:
    - change-visit-status-topic
    - remove-visit-topic
    - reception-removed-topic
  num-of-partitions: 1
  replication-factor: 1

kafka-producer-config:
  key-serializer-class: org.apache.kafka.common.serialization.StringSerializer
  value-serializer-class: org.springframework.kafka.support.serializer.JsonSerializer
  compression-type: snappy
  acks: all
  batch-size: 16384
  batch-size-boost-factor: 100
  linger-ms: 5
  request-timeout-ms: 60000
  retry-count: 5

kafka-consumer-config:
  key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
  value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
  consumer-group-id: visit-topic-consumer
  auto-offset-reset: earliest
  trusted-package: "*"
  #  specific-avro-reader-key: specific.avro.reader
  #  specific-avro-reader: true
  batch-listener: true
  auto-startup: true
  concurrency-level: 3
  session-timeout-ms: 10000
  heartbeat-interval-ms: 3000
  max-poll-interval-ms: 300000
  max-poll-records: 500
  max-partition-fetch-bytes-default: 1048576
  max-partition-fetch-bytes-boost-factor: 1
  poll-timeout-ms: 150


logging:
  file.name: logs/reception_cmd_ms.log
axon:
  serializer:
    general: jackson
    events: jackson
    messages: jackson
reception-created-topic: "reception-created-topic"