spring:
  application:
    name: RECEPTION-CMD-MS
  cloud:
    config:
      allow-override: true
      override-none: true
      name: reception-cmd-ms
  config:
    import: 'configserver:'
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      default-zone: http://localhost:8761/eureka
  instance:
    prefer-ip-address: true
#  profiles:
#    active: docker

management:
  tracing:
    sampling:
      probability: 1.0