server:
  port: 8888
spring:
  application:
    name: configserver
  cloud:
    config:
      server:
        git:
          uri: https://github.com/pezhmantp/config-server-repository
          clone-on-start: true
        bootstrap: true
    fail-fast: true