spring:
  application:
    name: API-GATEWAY
  config:
    import: configserver:http://localhost:8888
management:
  tracing:
    sampling:
      probability: 1.0
  endpoints:
    web:
      exposure:
        include: health, info, circuitbreakers
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka
#  instance:
#    hostname: localhost

