spring:
  application:
    name: API-GATEWAY
  cloud:
    config:
      allow-override: true
      override-none: true
      name: api-gateway
  config:
    import: 'configserver:'
#management:
#  tracing:
#    sampling:
#      probability: 1.0
#  endpoints:
#    web:
#      exposure:
#        include: health, info, circuitbreakers
#management:
#  endpoints:
#    web:
#      base-path: /actuator
#      exposure.include: health, prometheus, gateway
#      path-mapping.prometheus: metrics
#  endpoint:
#    health:
#      show-details: always
#    prometheus:
#      cache.time-to-live: 1ms
#    gateway:
#      enabled: true
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      default-zone: http://localhost:8761/eureka
  instance:
    prefer-ip-address: true
#    hostname: localhost
#    hostname: service-registry-app

