eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      default-zone: http://localhost:8761/eureka
  instance:
    prefer-ip-address: true
spring:
  application:
    name: PHARMACY-QUERY-MS
  cloud:
    config:
      allow-override: true
      override-none: true
      name: pharmacy-query-ms
  config:
    import: 'configserver:'
axon:
  axonserver:
    servers: localhost:8124
  serializer:
    general: jackson
    events: jackson
    messages: jackson
management:
  tracing:
    sampling:
      probability: 1.0