server:
  port: 9095
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      default-zone: http://localhost:8761/eureka
spring:
  application:
    name: PHARMACY-QUERY-MS
  datasource:
    url: jdbc:mysql://localhost:3306/pharmacy_db?createDatabaseIfNotExist=true
    username: root
    password: myhawramRootPsw1
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQL8Dialect
    show-sql: true
axon:
  #  axonserver:
  #    servers: localhost:8123
  serializer:
    general: jackson
    events: jackson
    messages: jackson