eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      default-zone: http://localhost:8761/eureka
  instance:
    prefer-ip-address: true
spring:
  application:
    name: PHARMACY-CMD-MS
  config:
    import: configserver:http://localhost:8888
axon:
  #  axonserver:
  #    servers: localhost:8123
  serializer:
    general: jackson
    events: jackson
    messages: jackson
management:
  tracing:
    sampling:
      probability: 1.0