server:
  port: 8092
spring:
  application:
    name: VISIT-QUERY-MS
  datasource:
    url: jdbc:mysql://localhost:3306/visit_db?createDatabaseIfNotExist=true
    username: root
    password: myhawramRootPsw1
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQL8Dialect
    show-sql: true
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      default-zone: http://localhost:8761/eureka
  instance:
    prefer-ip-address: true
axon:
#  axonserver:
#    servers: localhost:8123
  serializer:
    general: jackson
    events: jackson
    messages: jackson
management:
  tracing:
    sampling:
      probability: 1.0
