spring:
  application:
    name: VISIT-QUERY-MS
  cloud:
    config:
      allow-override: true
      override-none: true
      name: visit-query-ms
  config:
    import: 'configserver:'
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      default-zone: http://localhost:8761/eureka
  instance:
    prefer-ip-address: true

management:
  tracing:
    sampling:
      probability: 1.0
