spring:
  application:
    name: LABORATORY-CMD-MS
  config:
    import: configserver:http://localhost:8888
  #  profiles:
  #    active: docker

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      default-zone: http://localhost:8761/eureka
  instance:
    prefer-ip-address: true
axon:
  axonserver:
    servers: localhost:8123
  serializer:
    general: jackson
    events: jackson
    messages: jackson
management:
  tracing:
    sampling:
      probability: 1.0
