spring:
  application:
    name: PATIENT-CMD-MS
  cloud:
    config:
      allow-override: true
      override-none: true
      name: patient-cmd-ms
  config:
    import: 'configserver:'
#  profiles:
#    active: docker
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      default-zone: http://localhost:8761/eureka
  instance:
    prefer-ip-address: true
management:
  zipkin:
    tracing:
      endpoint: http://localhost:9411
  tracing:
    sampling:
      probability: 1.0