server:
  port: 8085
spring:
  application:
    name: reception_query_ms
  datasource:
    url: jdbc:mysql://mysql-docker-compose:3306/reception2_db?createDatabaseIfNotExist=true
    username: root
    password: myhawramRootPsw1
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQL8Dialect
    show-sql: true
logging:
  file.name: logs/reception_query_ms.log
axon:
  axonserver:
    servers: axon-docker-compose:8124
  serializer:
    general: jackson
    events: jackson
    messages: jackson

