spring:
  application:
    name: PATIENT-QUERY-MS
  config:
    import: configserver:http://localhost:8888
#  profiles:
#    active: docker
axon:
  serializer:
    general: jackson
    events: jackson
    messages: jackson
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      default-zone: http://localhost:8761/eureka
  instance:
    prefer-ip-address: true
management:
  #  zipkin:
  #    tracing:
  #      endpoint: http://localhost:9411
  tracing:
    sampling:
      probability: 1.0