server:
  port: 8081
spring:
  application:
    name: patient_query_ms
  datasource:
    url: jdbc:mysql://localhost:3306/patient_db?createDatabaseIfNotExist=true
    username: root
    password: myhawramRootPsw1
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQL8Dialect
    show-sql: true
axon:
  serializer:
    general: jackson
    events: jackson
    messages: jackson